import { AppSettings, GameColorDef, GameColorName, PlayerStats, ShapeType, ThemeDefinition, ThemeId, UserProfile } from '../models/types';

export const GAME_COLORS: Record<GameColorName, GameColorDef> = {
  red: {
    name: 'red',
    hex: '#FF2E63',
    bgClass: 'bg-[#FF2E63]',
    borderClass: 'border-[#FF2E63]',
    label: 'RED',
    glow: 'rgba(255, 46, 99, 0.45)',
  },
  blue: {
    name: 'blue',
    hex: '#08D9D6',
    bgClass: 'bg-[#08D9D6]',
    borderClass: 'border-[#08D9D6]',
    label: 'BLUE',
    glow: 'rgba(8, 217, 214, 0.45)',
  },
  green: {
    name: 'green',
    hex: '#25E68C',
    bgClass: 'bg-[#25E68C]',
    borderClass: 'border-[#25E68C]',
    label: 'GRE',
    glow: 'rgba(37, 230, 140, 0.45)',
  },
  yellow: {
    name: 'yellow',
    hex: '#FFDE59',
    bgClass: 'bg-[#FFDE59]',
    borderClass: 'border-[#FFDE59]',
    label: 'YEL',
    glow: 'rgba(255, 222, 89, 0.45)',
  },
  purple: {
    name: 'purple',
    hex: '#9D4EDD',
    bgClass: 'bg-[#9D4EDD]',
    borderClass: 'border-[#9D4EDD]',
    label: 'PUR',
    glow: 'rgba(157, 78, 221, 0.45)',
  },
  orange: {
    name: 'orange',
    hex: '#FF9F1C',
    bgClass: 'bg-[#FF9F1C]',
    borderClass: 'border-[#FF9F1C]',
    label: 'ORA',
    glow: 'rgba(255, 159, 28, 0.45)',
  },
  pink: {
    name: 'pink',
    hex: '#FF66B2',
    bgClass: 'bg-[#FF66B2]',
    borderClass: 'border-[#FF66B2]',
    label: 'PNK',
    glow: 'rgba(255, 102, 178, 0.45)',
  },
  cyan: {
    name: 'cyan',
    hex: '#00F0FF',
    bgClass: 'bg-[#00F0FF]',
    borderClass: 'border-[#00F0FF]',
    label: 'CYN',
    glow: 'rgba(0, 240, 255, 0.45)',
  },
  lime: {
    name: 'lime',
    hex: '#70FF00',
    bgClass: 'bg-[#70FF00]',
    borderClass: 'border-[#70FF00]',
    label: 'LIM',
    glow: 'rgba(112, 255, 0, 0.45)',
  },
  amber: {
    name: 'amber',
    hex: '#FFB703',
    bgClass: 'bg-[#FFB703]',
    borderClass: 'border-[#FFB703]',
    label: 'AMB',
    glow: 'rgba(255, 183, 3, 0.45)',
  },
};

export const COLOR_NAMES: GameColorName[] = ['red', 'blue', 'green', 'yellow', 'purple', 'orange', 'pink', 'cyan', 'lime', 'amber'];
export const COLOR_KEYS = COLOR_NAMES;

export const SHAPE_TYPES: ShapeType[] = ['circle', 'square', 'triangle', 'diamond', 'star'];
export const SHAPE_KEYS = SHAPE_TYPES;

export const THEMES: Record<ThemeId, ThemeDefinition> = {
  classic: {
    id: 'classic',
    name: 'Arcade Classic',
    description: 'Electric cyan and neon vibrancy designed for crisp visibility.',
    bgGradient: 'from-[#0A0E17] via-[#0F172A] to-[#0A0E17]',
    cardBg: 'bg-[#131A29]',
    cardBorder: 'border-cyan-500/20',
    accentColor: 'text-cyan-400',
    accentHex: '#00F0FF',
    unlocked: true,
    priceCoins: 0,
    previewColors: ['#FF2E63', '#08D9D6', '#25E68C'],
  },
  neon: {
    id: 'neon',
    name: 'Cyber Neon',
    description: 'Ultra-saturated cyber colors inspired by Tokyo nightlife.',
    bgGradient: 'from-[#120024] via-[#1A0033] to-[#0A0017]',
    cardBg: 'bg-[#22003D]',
    cardBorder: 'border-fuchsia-500/30',
    accentColor: 'text-fuchsia-400',
    accentHex: '#FF007F',
    unlocked: false,
    priceCoins: 500,
    previewColors: ['#FF007F', '#00F0FF', '#FFE600'],
  },
  dark: {
    id: 'dark',
    name: 'Minimal OLED Dark',
    description: 'Pitch-black contrast for intense focus and battery efficiency.',
    bgGradient: 'from-[#000000] via-[#050505] to-[#000000]',
    cardBg: 'bg-[#0F0F0F]',
    cardBorder: 'border-white/10',
    accentColor: 'text-white',
    accentHex: '#FFFFFF',
    unlocked: false,
    priceCoins: 800,
    previewColors: ['#FFFFFF', '#888888', '#333333'],
  },
  space: {
    id: 'space',
    name: 'Deep Space',
    description: 'Cosmic nebula gradients and glowing starfield palettes.',
    bgGradient: 'from-[#03071E] via-[#0B092B] to-[#03071E]',
    cardBg: 'bg-[#110E38]',
    cardBorder: 'border-indigo-500/25',
    accentColor: 'text-indigo-400',
    accentHex: '#6366F1',
    unlocked: false,
    priceCoins: 1200,
    previewColors: ['#6366F1', '#EC4899', '#8B5CF6'],
  },
  candy: {
    id: 'candy',
    name: 'Sweet Candy',
    description: 'Playful pastel tones and high-contrast sweet shapes.',
    bgGradient: 'from-[#1F001A] via-[#2E0827] to-[#1F001A]',
    cardBg: 'bg-[#3D0C34]',
    cardBorder: 'border-pink-500/30',
    accentColor: 'text-pink-400',
    accentHex: '#F472B6',
    unlocked: false,
    priceCoins: 1500,
    previewColors: ['#F472B6', '#38BDF8', '#FACC15'],
  },
};

export const INITIAL_SETTINGS: AppSettings = {
  soundEnabled: true,
  musicEnabled: true,
  hapticsEnabled: true,
  notificationsEnabled: true,
  language: 'en',
  highContrastMode: false,
  colorBlindLabels: true,
  activeThemeId: 'classic',
};

export const INITIAL_STATS: PlayerStats = {
  userId: 'guest',
  bestScore: 0,
  highestCombo: 0,
  gamesPlayed: 0,
  correctAnswers: 0,
  wrongAnswers: 0,
  totalTaps: 0,
  fastestReactionMs: 0,
  totalReactionMs: 0,
  dailyBest: 0,
  dailyStreak: 0,
  lastDailyDate: '',
  dailyCompletedToday: false,
};

export const INITIAL_GUEST_USER: UserProfile = {
  id: 'guest-' + Math.random().toString(36).substring(2, 9),
  name: 'Guest Player',
  isGuest: true,
  phoneVerified: false,
  createdAt: new Date().toISOString(),
  lastLoginAt: new Date().toISOString(),
  platform: 'web',
};
